import { DM_Sans, Plus_Jakarta_Sans, Work_Sans } from "next/font/google";
import "./globals.css";

const font = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gray-100 antialiased text-sm ${font.className}`}>{children}</body>
    </html>
  );
}
